#############
# Carpenter #
#############
sdqt_carpenter = "Carpenter"
sdqd_carpenter = "Help the Winkelmanns to recreate their roof to get a nice reward."

#############
# Irmingard #
#############
sd_irmingard_hello = "Hey Christian, back in Bothel again?"
