item_name_modified = "%s_of_%s"

sd_of_adonis = "Adonis"

Shotgun_descr = "Ahandsomebarrelshotgun."

# --- Melee ---
Fists = "Fists"
Stone = "Stone"
Claws = "Claws"
IronRod = "IronRod"
BrokenBottle = "BrokenBottle"
KitchenKnife = "KitchenKnife"
Shiv = "Shiv"
Pipe = "Pipe"
BronzeKnuckles = "BronzeKnuckles"
SteelKnuckles = "SteelKnuckles"
Crowbar = "Crowbar"
Club = "Club"
ShortSword = "ShortSword"
Sword = "Sword"
LongSword = "LongSword"
SmallAxe = "SmallAxe"
MorningStar = "MorningStar"
Machete = "Machete"
Katana = "Katana"
Chainsword = "Chainsword"
CombatKnife = "CombatKnife"
Gladius = "Gladius"
WarAxe = "WarAxe"
BattleHammer = "BattleHammer"
Halberd = "Halberd"
Spear = "Spear"
PowerBlade = "PowerBlade"
ShockBaton = "ShockBaton"
ChainFlail = "ChainFlail"
PlasmaDagger = "PlasmaDagger"
PoweredKatana = "PoweredKatana"
VibroAxe = "VibroAxe"
PulseHammer = "PulseHammer"
GravityMace = "GravityMace"
MagBlade = "MagBlade"
EnergyScythe = "EnergyScythe"
PlasmaSword = "PlasmaSword"
OmegaBlade = "OmegaBlade"

# --- Bows --- #
IronRodBow = "IronRodBow"

# --- Arrows --- #
SteelArrow = "SteelArrow"
PoisonArrow = "PoisonArrow"
RamboArrow = "RamboArrow"

# --- Grenades --- #
Molotov = "Molotov"
PipeBomb = "PipeBomb"

# --- Firearms ---
PipePistol = "PipePistol"
RustyRevolver = "RustyRevolver"
RustyPistol = "RustyPistol"
Pistol = "Pistol"
SilencedPistol = "SilencedPistol"
Revolver = "Revolver"
CompactSMG = "CompactSMG"
SMG = "SubmachineGun"
TacticalSMG = "TacticalSMG"
Shotgun = "Shotgun"
AutoShotgun = "AutoShotgun"
HuntingRifle = "HuntingRifle"
AssaultRifle = "AssaultRifle"
Carbine = "Carbine"
SniperRifle = "SniperRifle"
BattleRifle = "BattleRifle"
LMG = "LightMachineGun"
HeavyLMG = "HeavyLMG"
Minigun = "Minigun"
GrenadeLauncher = "GrenadeLauncher"
RocketLauncher = "RocketLauncher"
Railgun = "Railgun"
LaserPistol = "LaserPistol"
LaserRifle = "LaserRifle"
PlasmaCarbine = "PlasmaCarbine"
PlasmaRifle = "PlasmaRifle"
PlasmaCannon = "PlasmaCannon"
GaussRifle = "GaussRifle"
IonBlaster = "IonBlaster"
PhotonSniper = "PhotonSniper"
DisruptorrCannon = "DisruptorCannon"
OmegaRailcannon = "OmegaRailcannon"

# --- Ammo ---
Ammo5mm = "Ammo5mm"
Ammo7mm = "Ammo7mm"
Ammo9mm = "Ammo9mm"
Ammo40mm = "Ammo40mm"
Ammo12g = "Shells12g"
Ammo45ACP = "Ammo.45ACP"
AmmoRPG = "RPGRocket"
AmmoEnergyCell = "EnergyCell"
AmmoRailSlug = "RailSlug"

# --- Armor ---
TShirt = "TShirt"
Clothes = "Clothes"
Pullover = "Pullover"
Jacket = "Jacket"
Hoodie = "Hoodie"
DenimJacket = "DenimJacket"
LeatherVest = "LeatherVest"
PaddedHoodie = "PaddedHoodie"
PaddedJacket = "PaddedJacket"
CombatVest = "CombatVest"
KevlarVest = "KevlarVest"
KevlarPanelVest = "KevlarPanelVest"
TacticalVest = "TacticalVest"
RiotArmor = "RiotArmor"
BallisticVest = "BallisticVest"
NanoFiberSuit = "NanofiberSuit"
PlateCarrierCeramic = "CeramicPlateCarrier"
PlateCarrierSteel = "SteelPlateCarrier"
UHMWPECarrier = "UHMWPECarrier"
SAPIPlateRig = "SAPIPlateRig"
FullTacticalRig = "FullTacticalRig"
BallisticCoat = "BallisticCoat"
GrapheneWeave = "GrapheneWeave"
LiquidArmorVest = "LiquidArmorVest"
CompositePlateRig = "CompositePlateRig"
SpallGuardCarrier = "SpallGuardCarrier"
RiotExoVest = "RiotExoVest"
SWATArmor = "SWATArmor"
CeramicSAPI4 = "CeramicSAPILevel4"
TitaniumCompositeRig = "TitaniumCompositeRig"
ReactivePlateVest = "ReactivePlateVest"
SmartFiberSuit = "SmartfiberSuit"
ExoPlateRig = "ExoPlateRig"
BallisticExosuit = "BallisticExosuit"
NanoCompositeCarapace = "NanoCompositeCarapace"
GrapheneCarapace = "GrapheneCarapace"
TitanWeaveSuit = "TitanWeaveSuit"
OblivionAegis = "OblivionAegis"

# --- Boots ---
Sandals = "Sandals"
FlipFlops = "FlipFlops"
RagShoes = "RagShoes"
WoolSlippers = "WoolSlippers"
Shoes = "Shoes"
WorkBoots = "WorkBoots"
Boots = "Boots"
Sneakers = "Sneakers"
SteelToes = "SteelToes"
CombatBoots = "CombatBoots"
TacticalWalkers = "TacticalWalkers"
ThermalTreads = "ThermalTreads"
SilentSteps = "SilentSteps"
UrbanGrips = "UrbanGrips"
NomadBoots = "NomadBoots"
AnkleGuards = "AnkleGuards"
RunnerBoots = "RunnerBoots"
PaddedStompers = "PaddedStompers"
GravBoots = "GravBoots"
ReinforcedHeels = "ReinforcedHeels"
SpiderClimbers = "SpiderClimbers"
ShockAbsorbers = "ShockAbsorbers"
MagStep = "MagStep"
VoidWalkers = "VoidWalkers"
StealthSoles = "StealthSoles"
RiotBoots = "RiotBoots"
BlastGuards = "BlastGuards"
HazmatTreads = "HazmatTreads"
ServoWalkers = "ServoWalkers"
AntiGravFeet = "AntiGravFeet"
PhaseBoots = "PhaseBoots"
NightStalkers = "NightStalkers"
TitanGreaves = "TitanGreaves"
WardenTreads = "WardenTreads"
OblivionStriders = "OblivionStriders"

# --- Trousers ---
Shorts = "Shorts"
Trousers = "Trousers"
Sweatpants = "Sweatpants"
TrackPants = "TrackPants"
Jeans = "Jeans"
CargoPants = "CargoPants"
ReinforcedPants = "ReinforcedPants"
PaddedPants = "PaddedPants"
CombatJeans = "CombatJeans"
KevlarLeggings = "KevlarLeggings"
TacticalPants = "TacticalPants"
RiotGreaves = "RiotGreaves"
BallisticLeggings = "BallisticLeggings"
NanoFiberPants = "NanofiberPants"
CeramicKneeGuards = "CeramicKneeGuards"
UHMWPELeggings = "UHMWPELeggings"
SAPIThighPlates = "SAPIThighPlates"
FullTacticalPants = "FullTacticalPants"
BallisticOverpants = "BallisticOverpants"
GrapheneWeavePants = "GrapheneWeavePants"
LiquidArmorPants = "LiquidArmorPants"
CompositeGreaves = "CompositeGreaves"
SpallGuardGreaves = "SpallGuardGreaves"
RiotExoGreaves = "RiotExoGreaves"
SWATLegArmor = "SWATLegArmor"
CeramicSAPI4Legs = "CeramicSAPI4Legs"
TitaniumCompositeLegs = "TitaniumCompositeLegs"
ReactivePlateLegs = "ReactivePlateLegs"
SmartFiberPants = "SmartfiberPants"
ExoLegRig = "ExoLegRig"
BallisticExoLegs = "BallisticExoLegs"
NanoCompositeCuisses = "NanoCompositeCuisses"
GrapheneCuisses = "GrapheneCuisses"
TitanWeaveCuisses = "TitanWeaveCuisses"
OblivionCuisses = "OblivionCuisses"

# --- Gloves ---
RagWraps = "RagWraps"
FingerlessGloves = "FingerlessGloves"
Gloves = "Gloves"
WoolGloves = "WoolGloves"
WorkGloves = "WorkGloves"
GripMitts = "GripMitts"
PaddedGloves = "PaddedGloves"
CombatGloves = "CombatGloves"
TacticalGrips = "TacticalGrips"
LeatherWraps = "LeatherWraps"
KnucklePads = "KnucklePads"
ShockGloves = "ShockGloves"
FrictionSkins = "FrictionSkins"
ThermalMitts = "ThermalMitts"
CarbonKnuckles = "CarbonKnuckles"
ArmorWeaveGloves = "ArmorWeaveGloves"
ServoFingers = "ServoFingers"
AntiSlashGloves = "AntiSlashGloves"
SparkGuards = "SparkGuards"
ClimbClaws = "ClimbClaws"
MagGripGloves = "MagGripGloves"
BioPulseGloves = "BioPulseGloves"
CryoGraspers = "CryoGraspers"
HazmatGloves = "HazmatGloves"
StealthGrips = "StealthGrips"
NeuroTouchGloves = "NeuroTouchGloves"
PhaseGrips = "PhaseGrips"
GauntletMK1 = "GauntletMK1"
TitanHands = "TitanHands"
GravPalms = "GravPalms"
WardenGloves = "WardenGloves"
OblivionClaws = "OblivionClaws"

# --- Helmets ---
TinfoilCap = "TinfoilCap"
Beanie = "Beanie"
DuctTapeHood = "DuctTapeHood"
BaseballCap = "BaseballCap"
SkiMask = "SkiMask"
GuyFawkesMask = "GuyFawkesMask"
LeatherHood = "LeatherHood"
BikeHelmet = "BikeHelmet"
CombatHelmet = "CombatHelmet"
GasMask = "GasMask"
RiotHelmet = "RiotHelmet"
VisorHelmet = "VisorHelmet"
DigitalHalo = "DigitalHalo"
QuantumVisor = "QuantumVisor"
Balaclava = "Balaclava"
TacticalHood = "TacticalHood"
KevlarCap = "KevlarCap"
StealthDome = "StealthDome"
CryoHelmet = "CryoHelmet"
DroneMask = "DroneMask"
EchoVisor = "EchoVisor"
FirewallHelmet = "FirewallHelmet"
ReflectiveHelm = "ReflectiveHelm"
EMPCap = "EMPCap"
ServoCrown = "ServoCrown"
NeuroShield = "NeuroShield"
HardenedSkull = "HardenedSkull"
PolymeshHelm = "PolyMeshHelm"
BioScannerCap = "BioScannerCap"
Shadowvisor = "ShadowVisor"
MechHelm = "MechHelm"
OblivionCrown = "OblivionCrown"
NovaCrest = "NovaCrest"

# --- Rings ---
PlasticBand = "PlasticBand"
CopperLoop = "CopperLoop"
SteelBand = "SteelBand"
Ring = "Ring"
SignetRing = "SignetRing"
LuckyBand = "LuckyBand"
CourierSignet = "CourierSignet"
MechanicBand = "MechanicBand"
MedtechLoop = "MedtechLoop"
QuietStepRing = "QuietStepRing"
KnuckleGuard = "KnuckleGuard"
BruteSeal = "BruteSeal"
RingOfTruth = "RingofTruth"
QuartermasterSeal = "QuartermasterSeal"
BackdoorSignet = "BackdoorSignet"
NetrunnerLoop = "NetrunnerLoop"
AdrenalineBand = "AdrenalineBand"
StabilizerRing = "StabilizerRing"
PulseSyncRing = "PulseSyncRing"
WardLoop = "WardLoop"
WeddingRing = "WeddingRing"
AegisRing = "AegisRing"
ShadowBond = "ShadowBond"
OmniPass = "OmniPass"
PhaseBand = "PhaseBand"
TitanBand = "TitanBand"
NeuroLinkRing = "NeuroLinkRing"
GravClampRing = "GravClampRing"
EchoRing = "EchoRing"
WardenSignet = "WardenSignet"
OblivionSeal = "OblivionSeal"
RingOfFire = "RingofFire"
RingOfWind = "RingofWind"

# --- Amulets ---
StringCharm = "StringCharm"
TinLocket = "TinLocket"
CopperTalisman = "CopperTalisman"
FibreCordSigil = "FibreCordSigil"
DogTagMk1 = "DogTagMk1"
StitchedRelic = "StitchedRelic"
GraphitePendant = "GraphitePendant"
PilgrimToken = "PilgrimToken"
SealOfFirstAid = "SealofFirstAid"
CourierMedallion = "CourierMedallion"
KnuckleboneCharm = "KnuckleboneCharm"
ColdIronAnkh = "ColdIronAnkh"
NetrunnerGlyph = "NetrunnerGlyph"
SmugglerToken = "SmugglerToken"
HexglassPendant = "HexglassPendant"
SaintedReliquary = "SaintedReliquary"
PulseDriverCharm = "PulseDriverCharm"
WardenScarab = "WardenScarab"
GhostLattice = "GhostLattice"
HazardRosary = "HazardRosary"
PhoenixVial = "PhoenixVial"
ArchivistSeal = "ArchivistSeal"
ScavengerCharm = "ScavengerCharm"
AegisHex = "AegisHex"
NullfieldCharm = "NullfieldCharm"
LoadbearingTotem = "LoadbearingTotem"
OverclockGlyph = "OverclockGlyph"
SilentshadeIcon = "SilentshadeIcon"
KismetMedal = "KismetMedal"
MarshalBadge = "MarshalBadge"
OblivionPhylactery = "OblivionPhylactery"
MonAmulet = "MonAmulet"
LionessAmulet = "LionessAmulet"

# --- Usable ---
Pen = "Pen"
MobilePhone = "MobilePhone"
Lighter = "Lighter"
Bottle = "Bottle"
Twig = "Twig"
Rags = "Rags"
Torch = "Torch"
DryTorch = "DryTorch"
Petrol = "Petrol"
Fireplace = "Fireplace"
Branch = "Branch"
Tissu = "Tissu"
WieldStick = "WieldStick"
Gunpowder = "Gunpowder"
Coal = "Coal"
Sulfur = "Sulfur"
Saltpeter = "Saltpeter"
Fuse = "Fuse"
WalkieTalkie = "WalkieTalkie"

# --- Heal ---
Painkiller = "Painkiller"
Medkit = "Medkit"
Stimulant = "Stimulant"

# --- Consumable ---
Coke = "Coke"
Pizza = "Pizza"
EnergyDrink = "EnergyDrink"
Sandwich = "Sandwich"
SmallBeer = "SmallBeer"
LargeBeer = "LargeBeer"
"Water1.5" = "Water1.5L"
"Water0.5" = "Water0.5L"
Hash = "Hash"
Apple = "Apple"
InstantNoodles = "InstantNoodles"
WaterBottle = "WaterBottle"
Cocaine = "Cocaine"
Speed = "Speed"
Extasy = "Extasy"
Weed = "Weed"

# --- Implants ---
NeuralJackLite = "NeuralJackLite"
CyberEyeI = "CyberEyeI"
DermalWeaveI = "DermalWeaveI"
MuscleWireI = "MuscleWireI"
ReflexBoosterI = "ReflexBoosterI"
CyberEyeII = "CyberEyeII"
DermalWeaveII = "DermalWeaveII"
NeuralLinkI = "NeuralLinkI"
BoneLacingI = "BoneLacingI"
TargetingOpticsI = "TargetingOpticsI"
DermalPlatingI = "DermalPlatingI"
CyberEyeIII = "CyberEyeIII"
ReflexBoosterII = "ReflexBoosterII"
MuscleWireII = "MuscleWireII"
SubdermalMesh = "SubdermalMesh"
TacticalHUD = "TacticalHUD"
NeuralCoProcessor = "NeuralCoProcessor"
DermalPlatingII = "DermalPlatingII"
EagleEyeSuite = "EagleEyeSuite"
TitaniumLacing = "TitaniumLacing"
SynapticAccelerator = "SynapticAccelerator"
NeuralLinkPro = "NeuralLinkPro"
ReactiveDermis = "ReactiveDermis"
GhostOptics = "GhostOptics"
WarplateUnderlay = "WarplateUnderlay"
OmegaEye = "OmegaEye"
TitanLacing = "TitanLacing"
NeuralOverclock = "NeuralOverclock"
PhaseDermis = "PhaseDermis"
GodSightArray = "GodSightArray"

# --- Decks ---
RhinoDeck = "RhinoDeck"
UserDeck = "UserDeck"
ControlDeck = "ControlDeck"
HackingDeck = "HackingDeck"
MetaDeck = "MetaDeck"

# --- EXE (do not translate) ---
"Move.exe" = "Move.exe"
"Strafe.exe" = "Strafe.exe"
"DMA.exe" = "DMA.exe"
"Ping4.exe" = "Ping4.exe"
"Ping6.exe" = "Ping6.exe"
"Backdoor.exe" = "Backdoor.exe"
"Rootkit.exe" = "Rootkit.exe"
"Modkit.exe" = "Modkit.exe"
"hydra.exe" = "hydra.exe"
"JTR.exe" = "JTR.exe"
"NMap.exe" = "NMap.exe"
"Trace.exe" = "Trace.exe"
"TraceNT.exe" = "TraceNT.exe"
"TraceNG.exe" = "TraceNG.exe"

# --- Quest Items ---
ArmyLetter = "ArmyLetter"
NoteGizmore = "NoteGizmore"
TheosPurse = "TheosPurse"

# --- Special ---
Nuyen = "Nuyen"

# --- Mounts --- #

Backpack = "Backpack"
Skateboard = "Skateboard"
OldBike = "OldBike"
RoadBike = "RoadBike"
MZ250 = "MZ250"
FordFiesta = "FordFiesta"
OpelKadett = "OpelKadett"
Famstar = "Famstar"
Calibra = "Calibra"
MercedesSL500 = "MercedesSL500"
