item_name_modified = "%s_of_%s"

# --- Melee ---
Fists = "Fäuste"
Claws = "Klauen"
Stone = "Stein"
BrokenBottle = "ZerbrocheneFlasche"
KitchenKnife = "Küchenmesser"
Shiv = "ImprovisiertesMesser"
Pipe = "Rohr"
BronzeKnuckles = "Bronze-Schlagring"
SteelKnuckles = "Stahl-Schlagring"
Crowbar = "Brechstange"
Club = "Keule"
ShortSword = "Kurzschwert"
Sword = "Schwert"
LongSword = "Langschwert"
SmallAxe = "Handaxt"
MorningStar = "Morgenstern"
Machete = "Machete"
Katana = "Katana"
Chainsword = "Kettenschwert"
CombatKnife = "Kampfmesser"
Gladius = "Gladius"
WarAxe = "Kriegsaxt"
BattleHammer = "Kriegshammer"
Halberd = "Hellebarde"
Spear = "Speer"
PowerBlade = "Kraftklinge"
ShockBaton = "Elektroschlagstock"
ChainFlail = "Kettenflegel"
PlasmaDagger = "Plasma-Dolch"
PoweredKatana = "Energie-Katana"
VibroAxe = "Vibro-Axt"
PulseHammer = "Impulshammer"
GravityMace = "Gravitationsstreitkolben"
MagBlade = "Magnetklinge"
EnergyScythe = "Energie-Sense"
PlasmaSword = "Plasma-Schwert"
OmegaBlade = "Omega-Klinge"

# --- Firearms ---
PipePistol = "Rohrpistole"
RustyRevolver = "RostigerRevolver"
RustyPistol = "RostigePistole"
Pistol = "Pistole"
SilencedPistol = "SchallgedämpftePistole"
Revolver = "Revolver"
CompactSMG = "KompakteMP"
SMG = "Maschinenpistole"
TacticalSMG = "TaktischeMP"
Shotgun = "Schrotflinte"
AutoShotgun = "Auto-Schrotflinte"
HuntingRifle = "Jagdgewehr"
AssaultRifle = "Sturmgewehr"
Carbine = "Karabiner"
SniperRifle = "Scharfschützengewehr"
BattleRifle = "Gefechtsgewehr"
LMG = "LeichtesMG"
HeavyLMG = "SchweresLMG"
Minigun = "Minigun"
GrenadeLauncher = "Granatwerfer"
RocketLauncher = "Raketenwerfer"
Railgun = "Railgun"
LaserPistol = "Laserpistole"
LaserRifle = "Lasergewehr"
PlasmaCarbine = "Plasma-Karabiner"
PlasmaRifle = "Plasma-Gewehr"
PlasmaCannon = "Plasma-Kanone"
GaussRifle = "Gauss-Gewehr"
IonBlaster = "Ionen-Blaster"
PhotonSniper = "Photonen-Scharfschützengewehr"
DisruptorrCannon = "Disruptor-Kanone"
OmegaRailcannon = "Omega-Railkanone"

# --- Ammo ---
Ammo5mm = "5mm-Munition"
Ammo7mm = "7mm-Munition"
Ammo9mm = "9mm-Munition"
Ammo40mm = "40mm-Munition"
Ammo12g = "12g-Schrot"
Ammo45ACP = ".45-ACP-Munition"
AmmoRPG = "RPG-Rakete"
AmmoEnergyCell = "Energiezelle"
AmmoRailSlug = "Rail-Projektil"

# --- Armor ---
TShirt = "T-Shirt"
Clothes = "Kleidung"
Jacket = "Jacke"
Hoodie = "Hoodie"
DenimJacket = "Jeansjacke"
LeatherVest = "Lederweste"
PaddedHoodie = "GepolsterterHoodie"
PaddedJacket = "GepolsterteJacke"
KevlarVest = "Kevlar-Weste"
KevlarPanelVest = "Kevlar-Plattenweste"
TacticalVest = "TaktischeWeste"
RiotArmor = "Riot-Rüstung"
BallisticVest = "BallistischeWeste"
NanoFiberSuit = "Nanofaser-Anzug"
PlateCarrierCeramic = "Plattenträger(Keramik)"
PlateCarrierSteel = "Plattenträger(Stahl)"
UHMWPECarrier = "UHMWPE-Träger"
SAPIPlateRig = "SAPI-Plattenträger"
FullTacticalRig = "TaktischesKomplett-Rig"
BallisticCoat = "BallistischerMantel"
GrapheneWeave = "Graphen-Gewebe"
LiquidArmorVest = "Flüssigpanzer-Weste"
CompositePlateRig = "Verbundplatten-Rig"
SpallGuardCarrier = "Splitterschutz-Träger"
RiotExoVest = "Riot-Exo-Weste"
SWATArmor = "SWAT-Rüstung"
CeramicSAPI4 = "Keramik-SAPIStufe4"
TitaniumCompositeRig = "Titan-Verbund-Rig"
ReactivePlateVest = "Reaktivplatten-Weste"
SmartFiberSuit = "Smartfaser-Anzug"
ExoPlateRig = "Exo-Platten-Rig"
BallisticExosuit = "BallistischerExoanzug"
NanoCompositeCarapace = "Nano-Verbund-Panzer"
GrapheneCarapace = "Graphen-Panzer"
TitanWeaveSuit = "Titan-Gewebeanzug"
OblivionAegis = "Oblivion-Ägis"

# --- Boots ---
Sandals = "Sandalen"
FlipFlops = "Flip-Flops"
RagShoes = "Lumpenschuhe"
WoolSlippers = "Wollpantoffeln"
Shoes = "Schuhe"
WorkBoots = "Arbeitsstiefel"
Boots = "Stiefel"
Sneakers = "Sneaker"
SteelToes = "Stahlkappenstiefel"
CombatBoots = "Kampfstiefel"
TacticalWalkers = "TaktischeLäufer"
ThermalTreads = "Thermo-Profile"
SilentSteps = "Leisetreter"
UrbanGrips = "Urban-Grips"
NomadBoots = "Nomadenstiefel"
AnkleGuards = "Knöchelschützer"
RunnerBoots = "Läuferstiefel"
PaddedStompers = "GepolsterteStampfer"
GravBoots = "Grav-Stiefel"
ReinforcedHeels = "VerstärkteAbsätze"
SpiderClimbers = "Spinnenkletterer"
ShockAbsorbers = "Stoßdämpfer"
MagStep = "Mag-Schritt"
VoidWalkers = "Leerenläufer"
StealthSoles = "Schleichsohlen"
RiotBoots = "Riot-Stiefel"
BlastGuards = "Explosionsschutz"
HazmatTreads = "Hazmat-Profile"
ServoWalkers = "Servo-Läufer"
AntiGravFeet = "Antigrav-Füße"
PhaseBoots = "Phasenstiefel"
NightStalkers = "Nachtpirscher"
TitanGreaves = "Titan-Beinschienen"
WardenTreads = "Wächter-Profile"
OblivionStriders = "Oblivion-Schreiter"

# --- Trousers ---
Shorts = "Shorts"
Trousers = "Hose"
Sweatpants = "Jogginghose"
TrackPants = "Trainingshose"
Jeans = "Jeans"
CargoPants = "Cargo-Hose"
ReinforcedPants = "VerstärkteHose"
PaddedPants = "GepolsterteHose"
KevlarLeggings = "Kevlar-Leggings"
TacticalPants = "TaktischeHose"
RiotGreaves = "Riot-Beinschienen"
BallisticLeggings = "BallistischeLeggings"
NanoFiberPants = "Nanofaser-Hose"
CeramicKneeGuards = "Keramik-Knieschützer"
UHMWPELeggings = "UHMWPE-Leggings"
SAPIThighPlates = "SAPI-Oberschenkelplatten"
FullTacticalPants = "TaktischeVollhose"
BallisticOverpants = "BallistischeÜberhose"
GrapheneWeavePants = "Graphen-Gewebehose"
LiquidArmorPants = "Flüssigpanzer-Hose"
CompositeGreaves = "Verbund-Beinschienen"
SpallGuardGreaves = "Splitterschutz-Beinschienen"
RiotExoGreaves = "Riot-Exo-Beine"
SWATLegArmor = "SWAT-Beinpanzer"
CeramicSAPI4Legs = "Keramik-SAPI4-Beine"
TitaniumCompositeLegs = "Titan-Verbund-Beine"
ReactivePlateLegs = "Reaktivplatten-Beine"
SmartFiberPants = "Smartfaser-Hose"
ExoLegRig = "Exo-Bein-Rig"
BallisticExoLegs = "BallistischeExobeine"
NanoCompositeCuisses = "Nano-Verbund-Cuisses"
GrapheneCuisses = "Graphen-Cuisses"
TitanWeaveCuisses = "Titan-Gewebe-Cuisses"
OblivionCuisses = "Oblivion-Cuisses"

# --- Gloves ---
RagWraps = "Lappenwickel"
FingerlessGloves = "FingerloseHandschuhe"
Gloves = "Handschuhe"
WoolGloves = "Wollhandschuhe"
WorkGloves = "Arbeitshandschuhe"
GripMitts = "Griff-Fäustlinge"
PaddedGloves = "GepolsterteHandschuhe"
CombatGloves = "Kampf-Handschuhe"
TacticalGrips = "Taktik-Griffe"
LeatherWraps = "Lederwickel"
KnucklePads = "Knöchelpads"
ShockGloves = "Schockhandschuhe"
FrictionSkins = "Reibhäute"
ThermalMitts = "Thermo-Fäustlinge"
CarbonKnuckles = "Carbon-Knöchel"
ArmorWeaveGloves = "Panzergewebe-Handschuhe"
ServoFingers = "Servo-Finger"
AntiSlashGloves = "Schnittschutz-Handschuhe"
SparkGuards = "Funken-Schützer"
ClimbClaws = "Kletterkrallen"
MagGripGloves = "Mag-Grip-Handschuhe"
BioPulseGloves = "Bio-Puls-Handschuhe"
CryoGraspers = "Kryo-Greifer"
HazmatGloves = "Hazmat-Handschuhe"
StealthGrips = "Schleich-Griffe"
NeuroTouchGloves = "Neuro-Touch-Handschuhe"
PhaseGrips = "Phasen-Griffe"
GauntletMK1 = "PanzerhandschuhMK1"
TitanHands = "Titanhände"
GravPalms = "Grav-Handflächen"
WardenGloves = "Wächter-Handschuhe"
OblivionClaws = "Oblivion-Krallen"

# --- Helmets ---
TinfoilCap = "Aluhut"
Beanie = "Beanie"
DuctTapeHood = "Panzertape-Haube"
BaseballCap = "Baseballkappe"
SkiMask = "Sturmhaube"
GuyFawkesMask = "Guy-Fawkes-Maske"
LeatherHood = "Lederhaube"
BikeHelmet = "Fahrradhelm"
CombatHelmet = "Kampfhelm"
GasMask = "Gasmaske"
RiotHelmet = "Riot-Helm"
VisorHelmet = "Visierhelm"
DigitalHalo = "DigitalerHeiligenschein"
QuantumVisor = "Quantenvisier"
Balaclava = "Balaklava"
TacticalHood = "Taktik-Haube"
KevlarCap = "Kevlar-Kappe"
StealthDome = "Schleichkuppel"
CryoHelmet = "Kryo-Helm"
DroneMask = "Drohnenmaske"
EchoVisor = "Echo-Visier"
FirewallHelmet = "Firewall-Helm"
ReflectiveHelm = "Reflexionshelm"
EMPCap = "EMP-Kappe"
ServoCrown = "Servo-Krone"
NeuroShield = "Neuro-Schild"
HardenedSkull = "GehärteterSchädel"
PolymeshHelm = "Poly-Mesh-Helm"
BioScannerCap = "Bio-Scanner-Kappe"
Shadowvisor = "Schattenvisier"
MechHelm = "Mech-Helm"
OblivionCrown = "Oblivion-Krone"
NovaCrest = "Nova-Kamm"

# --- Rings ---
PlasticBand = "Plastikband"
CopperLoop = "Kupferring"
SteelBand = "Stahlband"
Ring = "Ring"
SignetRing = "Siegelring"
LuckyBand = "Glücksband"
CourierSignet = "Kuriersiegel"
MechanicBand = "Mechanikerband"
MedtechLoop = "Medtech-Ring"
QuietStepRing = "Leisetritt-Ring"
KnuckleGuard = "Knöchelschutz"
BruteSeal = "Brutalsiegel"
RingOfTruth = "RingderWahrheit"
QuartermasterSeal = "Quartiermeister-Siegel"
BackdoorSignet = "Hintertür-Signet"
NetrunnerLoop = "Netrunner-Ring"
AdrenalineBand = "Adrenalinband"
StabilizerRing = "Stabilisator-Ring"
PulseSyncRing = "Puls-Sync-Ring"
WardLoop = "Schutz-Ring"
WeddingRing = "Ehering"
AegisRing = "Ägis-Ring"
ShadowBond = "Schattenbund"
OmniPass = "Omni-Pass"
PhaseBand = "Phasenband"
TitanBand = "Titanband"
NeuroLinkRing = "NeuroLink-Ring"
GravClampRing = "Grav-Klemmring"
EchoRing = "Echo-Ring"
WardenSignet = "Wächter-Siegel"
OblivionSeal = "Oblivion-Siegel"
RingOfFire = "RingdesFeuers"
RingOfWind = "RingdesWindes"

# --- Amulets ---
StringCharm = "Schnur-Talisman"
TinLocket = "Zinn-Medaillon"
CopperTalisman = "Kupfer-Talisman"
FibreCordSigil = "Faserband-Siegel"
DogTagMk1 = "HundemarkeMk1"
StitchedRelic = "GenähteReliquie"
GraphitePendant = "Graphit-Anhänger"
PilgrimToken = "Pilgerzeichen"
SealOfFirstAid = "SiegelderErstenHilfe"
CourierMedallion = "Kurier-Medaille"
KnuckleboneCharm = "Knöchelbein-Amulett"
ColdIronAnkh = "Kalteisen-Ankh"
NetrunnerGlyph = "Netrunner-Glyphe"
SmugglerToken = "Schmugglerzeichen"
HexglassPendant = "Hexglas-Anhänger"
SaintedReliquary = "GeweihteReliquie"
PulseDriverCharm = "Pulsantrieb-Amulett"
WardenScarab = "Wächter-Skarabäus"
GhostLattice = "Geistergitter"
HazardRosary = "Gefahren-Rosenkranz"
PhoenixVial = "Phönix-Phiole"
ArchivistSeal = "Archivisten-Siegel"
ScavengerCharm = "Plünderer-Amulett"
AegisHex = "Ägis-Hex"
NullfieldCharm = "Nullfeld-Amulett"
LoadbearingTotem = "Lastträger-Totem"
OverclockGlyph = "Übertaktungs-Glyphe"
SilentshadeIcon = "Schattenschleier-Ikone"
KismetMedal = "Kismet-Medaille"
MarshalBadge = "Marschall-Abzeichen"
OblivionPhylactery = "Oblivion-Phylakterium"
MonAmulet = "Mönchs-Amulett"
LionessAmulet = "Löwinnen-Amulett"

# --- Usable ---
Pen = "Stift"
MobilePhone = "Handy"
Lighter = "Feuerzeug"
Bottle = "Flasche"
Twig = "Ast"
Rags = "Lumpen"
Torch = "Fackel"
DryTorch = "TrockeneFackel"
Petrol = "Benzin"

# --- Heal ---
Medkit = "Medikit"
Stimulant = "Stimulans"

# --- Consumable ---
Coke = "Cola"
Pizza = "Pizza"
EnergyDrink = "Energydrink"
Sandwich = "Sandwich"
SmallBeer = "KleinesBier"
LargeBeer = "GroßesBier"
"Water1.5" = "Wasser1,5l"
"Water0.5" = "Wasser0,5l"
Hash = "Hasch"
Apple = "Apfel"
InstantNoodles = "Instant-Nudeln"
WaterBottle = "Wasserflasche"

# --- Implants ---
NeuralJackLite = "NeuralbuchseLite"
CyberEyeI = "Cyber-AugeI"
DermalWeaveI = "Dermal-GewebeI"
MuscleWireI = "Muskel-DrahtI"
ReflexBoosterI = "Reflex-BoosterI"
CyberEyeII = "Cyber-AugeII"
"DermalWeaveII" = "Dermal-GewebeII"
NeuralLinkI = "NeuralLinkI"
BoneLacingI = "Knochen-VerstärkungI"
TargetingOpticsI = "ZieloptikI"
DermalPlatingI = "Dermal-PanzerungI"
CyberEyeIII = "Cyber-AugeIII"
ReflexBoosterII = "Reflex-BoosterII"
MuscleWireII = "Muskel-DrahtII"
SubdermalMesh = "SubdermalesNetz"
TacticalHUD = "TaktischesHUD"
NeuralCoProcessor = "NeuralerCo-Prozessor"
DermalPlatingII = "Dermal-PanzerungII"
EagleEyeSuite = "Adlerauge-Suite"
TitaniumLacing = "Titan-Verstrebung"
SynapticAccelerator = "SynaptischerBeschleuniger"
NeuralLinkPro = "NeuralLinkPro"
ReactiveDermis = "ReaktiveDermis"
GhostOptics = "Geisteroptik"
WarplateUnderlay = "Kriegsplatten-Unterzug"
OmegaEye = "Omega-Auge"
TitanLacing = "Titan-Verstrebung"
NeuralOverclock = "NeuronalesOverclocking"
PhaseDermis = "Phasen-Dermis"
GodSightArray = "Gottessicht-Array"

# --- Decks ---
RhinoDeck = "Rhino-Deck"
UserDeck = "User-Deck"
ControlDeck = "Kontroll-Deck"
HackingDeck = "Hacker-Deck"
MetaDeck = "Meta-Deck"

# --- EXE (do not translate) ---
"Move.exe" = "Move.exe"
"Strafe.exe" = "Strafe.exe"
"DMA.exe" = "DMA.exe"
"Ping4.exe" = "Ping4.exe"
"Ping6.exe" = "Ping6.exe"
"Backdoor.exe" = "Backdoor.exe"
"Rootkit.exe" = "Rootkit.exe"
"Modkit.exe" = "Modkit.exe"
"hydra.exe" = "hydra.exe"
"JTR.exe" = "JTR.exe"
"NMap.exe" = "NMap.exe"
"Trace.exe" = "Trace.exe"
"TraceNT.exe" = "TraceNT.exe"
"TraceNG.exe" = "TraceNG.exe"

# --- Quest Items ---
ArmyLetter = "Armee-Brief"
NoteGizmore = "Notizvongizmore"
TheosPurse = "TheosGeldbörse"

# --- Special ---
Nuyen = "Nuyen"
