sdqs_ruth_hello = "Uh hello.... i am sick."
sdqs_ruth_work1 = "Oh you should get a job."
sdqs_ruth_work2 = "Oh you work at Obi now."
sdqs_ruth_work3 = "Oh you got an accident at Obi?"
sdqs_ruth_work4 = "Oh you still work at Obi?"
sdqs_ruth_weed = "What?"
sdqs_ruth_home = "Oh nice that Lazer is fine."
